============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..FFFFFFFFFFF                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:17: AttributeError
_______________________________ test_s_remove_1 ________________________________

    def test_s_remove_1():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:25: AttributeError
_______________________________ test_s_remove_2 ________________________________

    def test_s_remove_2():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:36: AttributeError
_______________________________ test_s_remove_3 ________________________________

    def test_s_remove_3():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:46: AttributeError
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:55: AttributeError
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
>       l.push(5)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:64: AttributeError
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_1 _________________________________

    def test_s_get_1():
        l = Ring()
>       l.push(10)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:84: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
>       l.push(10)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:92: AttributeError
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = Ring()
        try:
>           l.get(2)
E           AttributeError: Ring instance has no attribute 'get'

test_student.py:101: AttributeError
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
>       l.push(1)
E       AttributeError: Ring instance has no attribute 'push'

test_student.py:109: AttributeError
===================== 11 failed, 2 passed in 0.20 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFFFFFF                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fa4ca2f7320>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:162: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_1 _________________________________

    def test_s_get_1():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(0) == 10
E       AttributeError: Ring instance has no attribute 'get'

test_student.py:87: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       AttributeError: Ring instance has no attribute 'get'

test_student.py:95: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = Ring()
        try:
>           l.get(2)
E           AttributeError: Ring instance has no attribute 'get'

test_student.py:101: AttributeError
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       AttributeError: Ring instance has no attribute 'get'

test_student.py:112: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 8 failed, 5 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7ff04e5b53b0>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:162: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff04e5d9638>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff04e5d9638>> = <assignment4.a04.Ring instance at 0x7ff04e5d9638>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff04e340878>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff04e340878>> = <assignment4.a04.Ring instance at 0x7ff04e340878>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 6 failed, 7 passed in 0.06 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py F.F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_1 _________________________________

    def test_s_len_1():
        l = Ring()
        l.insert(0, 5)
        l.insert(0, 6)
    
>       assert l.len() == 2
E       assert 1 == 2
E        +  where 1 = <bound method Ring.len of <assignment4.a04.Ring instance at 0x7fa21d4a8b00>>()
E        +    where <bound method Ring.len of <assignment4.a04.Ring instance at 0x7fa21d4a8b00>> = <assignment4.a04.Ring instance at 0x7fa21d4a8b00>.len

test_student.py:9: AssertionError
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fa21d4b7248>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
>       while temp.next != self.head:
E       AttributeError: 'NoneType' object has no attribute 'next'

a04.py:161: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fa21d238680>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fa21d238680>> = <assignment4.a04.Ring instance at 0x7fa21d238680>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fa21d4c7e60>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fa21d4c7e60>> = <assignment4.a04.Ring instance at 0x7fa21d4c7e60>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 7 failed, 6 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 0 items / 1 errors

==================================== ERRORS ====================================
_______________________ ERROR collecting test_student.py _______________________
/usr/local/lib/python2.7/dist-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:294: in load_module
    six.exec_(co, mod.__dict__)
../../.local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
<string>:1: in <module>
    ???
test_student.py:1: in <module>
    from a04 import Ring
E     File "/home/an0nym0us/Desktop/assignment4/a04.py", line 150
E       def len(self):
E      ^
E   IndentationError: unexpected indent
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.22 seconds ============================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 0 items / 1 errors

==================================== ERRORS ====================================
_______________________ ERROR collecting test_student.py _______________________
/usr/local/lib/python2.7/dist-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:294: in load_module
    six.exec_(co, mod.__dict__)
../../.local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
<string>:1: in <module>
    ???
test_student.py:1: in <module>
    from a04 import Ring
E     File "/home/an0nym0us/Desktop/assignment4/a04.py", line 150
E       def len(self):
E      ^
E   IndentationError: unexpected indent
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.17 seconds ============================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py FFF...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_1 _________________________________

    def test_s_len_1():
        l = Ring()
        l.insert(0, 5)
        l.insert(0, 6)
    
>       assert l.len() == 2
E       assert 1 == 2
E        +  where 1 = <bound method Ring.len of <assignment4.a04.Ring instance at 0x7fe4f3564ab8>>()
E        +    where <bound method Ring.len of <assignment4.a04.Ring instance at 0x7fe4f3564ab8>> = <assignment4.a04.Ring instance at 0x7fe4f3564ab8>.len

test_student.py:9: AssertionError
_________________________________ test_s_len_2 _________________________________

    def test_s_len_2():
        l = Ring()
>       assert l.len() == 0

test_student.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fe4f35cca28>

    def len(self):
    
        count = 0
>       temp = self.head.next
E       AttributeError: 'NoneType' object has no attribute 'next'

a04.py:153: AttributeError
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fe4f35a9368>

    def len(self):
    
        count = 0
        temp = self.head.next
    
        while temp != self.head:
            count += 1
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:157: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fe4f3302b90>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fe4f3302b90>> = <assignment4.a04.Ring instance at 0x7fe4f3302b90>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fe4f356f7e8>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fe4f356f7e8>> = <assignment4.a04.Ring instance at 0x7fe4f356f7e8>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 8 failed, 5 passed in 0.09 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fb74127a3b0>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:162: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fb74129e488>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fb74129e488>> = <assignment4.a04.Ring instance at 0x7fb74129e488>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fb7410054d0>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fb7410054d0>> = <assignment4.a04.Ring instance at 0x7fb7410054d0>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 6 failed, 7 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f84c8b66290>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:162: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f84c88f60e0>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f84c88f60e0>> = <assignment4.a04.Ring instance at 0x7f84c88f60e0>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f84c88ff7a0>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f84c88ff7a0>> = <assignment4.a04.Ring instance at 0x7f84c88ff7a0>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 6 failed, 7 passed in 0.06 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fddf2c35290>

    def len(self):
    
        if self.head is None:
            return 0
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:162: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fddf29c50e0>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fddf29c50e0>> = <assignment4.a04.Ring instance at 0x7fddf29c50e0>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fddf29ce5f0>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7fddf29ce5f0>> = <assignment4.a04.Ring instance at 0x7fddf29ce5f0>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 6 failed, 7 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f3f4089a3b0>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:163: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_1 ______________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_2 ______________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
______________________________ test_s_remove_at_3 ______________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f3f4061d488>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f3f4061d488>> = <assignment4.a04.Ring instance at 0x7f3f4061d488>.get

test_student.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
_________________________________ test_s_get_4 _________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f3f406244d0>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7f3f406244d0>> = <assignment4.a04.Ring instance at 0x7f3f406244d0>.get

test_student.py:112: AssertionError
----------------------------- Captured stdout call -----------------------------
1st Case
====================== 6 failed, 7 passed in 0.08 seconds ======================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF.F.F                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7ff976a563b0>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:163: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_1 _________________________________________________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_2 _________________________________________________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_3 _________________________________________________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
____________________________________________________________________ test_s_get_2 ____________________________________________________________________

    def test_s_get_2():
        l = Ring()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11
E       assert 10 == 11
E        +  where 10 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff9767d8488>>(1)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff9767d8488>> = <assignment4.a04.Ring instance at 0x7ff9767d8488>.get

test_student.py:95: AssertionError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
____________________________________________________________________ test_s_get_4 ____________________________________________________________________

    def test_s_get_4():
        l = Ring()
        l.push(1)
        l.push(2)
        l.push(4)
>       assert l.get(5) == 4
E       assert 2 == 4
E        +  where 2 = <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff9767df4d0>>(5)
E        +    where <bound method Ring.get of <assignment4.a04.Ring instance at 0x7ff9767df4d0>> = <assignment4.a04.Ring instance at 0x7ff9767df4d0>.get

test_student.py:112: AssertionError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
========================================================= 6 failed, 7 passed in 0.08 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF....                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f8c36df33b0>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:163: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_1 _________________________________________________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_2 _________________________________________________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_3 _________________________________________________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
========================================================= 4 failed, 9 passed in 0.06 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py F.F...FFF....                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_1 ____________________________________________________________________

    def test_s_len_1():
        l = Ring()
        l.insert(0, 5)
        l.insert(0, 6)
    
>       assert l.len() == 2
E       assert 1 == 2
E        +  where 1 = <bound method Ring.len of <assignment4.a04.Ring instance at 0x7f01f053db00>>()
E        +    where <bound method Ring.len of <assignment4.a04.Ring instance at 0x7f01f053db00>> = <assignment4.a04.Ring instance at 0x7f01f053db00>.len

test_student.py:9: AssertionError
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f01f0550680>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 0
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:163: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_1 _________________________________________________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_2 _________________________________________________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_3 _________________________________________________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
========================================================= 5 failed, 8 passed in 0.06 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F...FFF....                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f90d5bfc3b0>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:163: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_1 _________________________________________________________________

    def test_s_remove_at_1():
        l = Ring()
        l.push(5)
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:56: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_2 _________________________________________________________________

    def test_s_remove_at_2():
        l = Ring()
        l.push(5)
        l.push(8)
>       l.remove_at(1)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:66: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
_________________________________________________________________ test_s_remove_at_3 _________________________________________________________________

    def test_s_remove_at_3():
        l = Ring()
>       l.remove_at(0)
E       AttributeError: Ring instance has no attribute 'remove_at'

test_student.py:75: AttributeError
========================================================= 4 failed, 9 passed in 0.06 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F..........                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7ff7d2c263f8>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:189: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
======================================================== 1 failed, 12 passed in 0.06 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py F.F..........                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_1 ____________________________________________________________________

    def test_s_len_1():
        l = Ring()
        l.insert(0, 5)
        l.insert(0, 6)
    
>       assert l.len() == 2
E       assert 1 == 2
E        +  where 1 = <bound method Ring.len of <assignment4.a04.Ring instance at 0x7f4ac7aceb48>>()
E        +    where <bound method Ring.len of <assignment4.a04.Ring instance at 0x7f4ac7aceb48>> = <assignment4.a04.Ring instance at 0x7f4ac7aceb48>.len

test_student.py:9: AssertionError
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f4ac7adc200>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 0
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:189: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
======================================================== 2 failed, 11 passed in 0.06 seconds =========================================================
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F..........                                                                                                                  [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________________ test_s_len_3 ____________________________________________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7f18496d03f8>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:189: AttributeError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
1st Case
======================================================== 1 failed, 12 passed in 0.06 seconds =========================================================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F..........                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fc6544833f8>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:189: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
===================== 1 failed, 12 passed in 0.05 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py ..F..........                                            [100%]

=================================== FAILURES ===================================
_________________________________ test_s_len_3 _________________________________

    def test_s_len_3():
        l = Ring()
        l.push(5)
        l.push(2)
        l.pop()
    
>       assert l.len() == 1

test_student.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment4.a04.Ring instance at 0x7fcd604ce3f8>

    def len(self):
    
        if self.head is None:
            return 0
    
        if self.head.next == self.head:
            return 1
    
        counter = 1
        temp = self.head.next
    
    
        while temp != self.head:
>           temp = temp.next
E           AttributeError: 'NoneType' object has no attribute 'next'

a04.py:189: AttributeError
----------------------------- Captured stdout call -----------------------------
1st Case
===================== 1 failed, 12 passed in 0.05 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/an0nym0us/Desktop/assignment4, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 13 items

test_student.py .............                                            [100%]

========================== 13 passed in 0.03 seconds ===========================
