============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py ......FF                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11

test_student.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7fdae8645ab8>, index = 1

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7fdae8601098>, index = 2

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
====================== 2 failed, 6 passed in 0.23 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py ......FF                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11

test_student.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7ff5293c7320>, index = 1

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7ff529446950>, index = 2

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
====================== 2 failed, 6 passed in 0.09 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py ......FF                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_2 _________________________________

    def test_s_get_2():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
>       assert l.get(1) == 11

test_student.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7fbbdada6320>, index = 1

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7fbbdad31908>, index = 2

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
    
>       if l.len() < index:
E       NameError: global name 'l' is not defined

a03.py:141: NameError
====================== 2 failed, 6 passed in 0.09 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7f808c0dd6c8>, index = 2

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
        counter = 0
    
    
    
        try:
            while temp is not None:
                temp = temp.next
                counter += 1
    
                if counter == index:
>                   return temp.val
E                   AttributeError: 'NoneType' object has no attribute 'val'

a03.py:150: AttributeError
====================== 1 failed, 7 passed in 0.09 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7f2e062285f0>, index = 2

    def get(self,index):
    
        temp = self.head
    
        if index == 0:
            return temp.val
    
        counter = 0
    
    
    
        try:
            while temp is not None:
                temp = temp.next
                counter += 1
    
                if counter == index:
>                   return temp.val
E                   AttributeError: 'NoneType' object has no attribute 'val'

a03.py:150: AttributeError
====================== 1 failed, 7 passed in 0.08 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 0 items / 1 errors

==================================== ERRORS ====================================
_______________________ ERROR collecting test_student.py _______________________
/usr/local/lib/python2.7/dist-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:294: in load_module
    six.exec_(co, mod.__dict__)
/home/an0nym0us/.local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
<string>:1: in <module>
    ???
test_student.py:1: in <module>
    from a03 import LinkedList
E     File "/media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3/a03.py", line 149
E       return temp.val
E            ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.27 seconds ============================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.08 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.07 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.09 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
            l.get(2)
>           raise AssertionError("IndexError not raised as expected!")
E           AssertionError: IndexError not raised as expected!

test_student.py:78: AssertionError
====================== 1 failed, 7 passed in 0.08 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 0 items / 1 errors

==================================== ERRORS ====================================
_______________________ ERROR collecting test_student.py _______________________
/usr/local/lib/python2.7/dist-packages/_pytest/python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:294: in load_module
    six.exec_(co, mod.__dict__)
/home/an0nym0us/.local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
<string>:1: in <module>
    ???
test_student.py:1: in <module>
    from a03 import LinkedList
E     File "/media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3/a03.py", line 147
E       return temp.val
E            ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.17 seconds ============================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7ff13ec7d758>, index = 2

    def get(self , index):
    
    
        temp = self.head
        counter = 0
    
    
        if index == 0:
            return temp.val
    
        while temp is not None and counter < index:
            prev = temp
            temp = temp.next
            counter += 1
    
        if counter == index:
>           return temp.val
E           AttributeError: 'NoneType' object has no attribute 'val'

a03.py:149: AttributeError
====================== 1 failed, 7 passed in 0.23 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py .......F                                                 [100%]

=================================== FAILURES ===================================
_________________________________ test_s_get_3 _________________________________

    def test_s_get_3():
        l = LinkedList()
        l.push(10)
        l.push(11)
        l.push(12)
        l.pop()
        try:
>           l.get(2)

test_student.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <assignment3.a03.LinkedList instance at 0x7f84e6306758>, index = 2

    def get(self , index):
    
    
        temp = self.head
        counter = 0
    
    
        if index == 0:
            return temp.val
    
        while temp is not None and counter < index:
            prev = temp
            temp = temp.next
            counter += 1
    
        if counter == index:
>           return temp.val
E           AttributeError: 'NoneType' object has no attribute 'val'

a03.py:149: AttributeError
====================== 1 failed, 7 passed in 0.08 seconds ======================
============================= test session starts ==============================
platform linux2 -- Python 2.7.15+, pytest-3.10.1, py-1.8.0, pluggy-0.12.0
rootdir: /media/an0nym0us/Essentilas/University/semester-3/data-structures/course-assignments/assignment3, inifile:
plugins: timeout-1.3.3
timeout: 3.0s
timeout method: signal
timeout func_only: False
collected 8 items

test_student.py ........                                                 [100%]

=========================== 8 passed in 0.05 seconds ===========================
